#!/bin/sh

# https://gist.github.com/ColCh/9d48693276aac50cac37a9fce23f9bda

protected_remote='upstream' 
remote="$1"

echo "---Running pre-push hook----"
if [ $remote = $protected_remote ]  
then  
  
    echo -en "\033[31mYou're about to push to upstream, is that what you intended? [y|n] \033[0m"
    echo -en "\033[1m"
    read -n 1 -r < /dev/tty
    echo -en "\033[0m"
    
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else  
    exit 0 # push will execute
fi